### ISSUE TITLE
UnicodeDecodeError on startup

### ISSUE THREAD

**Issue by rmcgibbo** [JukkaL/mypy#1017]
I got the following error on import. The offending file that triggers the error is a valid python3 file encoded in utf-8 (it has ``# -*- coding: utf-8 -*-`` at the top), but not ascii).

```
$ mypy --use-python-path myfile.py
Traceback (most recent call last):
  File "/Users/rmcgibbo/miniconda/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/main.py", line 49, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/main.py", line 92, in type_check_only
    python_path=options.python_path)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/build.py", line 383, in process
    next.process()
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/build.py", line 725, in process
    res = self.import_module(id)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/build.py", line 766, in import_module
    path, text = read_module_source_from_file(file_id, self.manager.lib_path)
  File "/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mypy/build.py", line 911, in read_module_source_from_file
    text = f.read()
  File "/Users/rmcgibbo/miniconda/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3037: ordinal not in range(128)
```

**Comment by darjus** [comment]
Related to #709 and #988

**Comment by rmcgibbo** [comment]
Sorry about that. I should have checked closer to see if it was a dupe.
