### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fullname'

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1029]
Full traceback:
```
Traceback (most recent call last):
  File "/Users/guido/src/mypy/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/Users/guido/src/mypy/mypy/main.py", line 49, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/guido/src/mypy/mypy/main.py", line 92, in type_check_only
    python_path=options.python_path)
  File "/Users/guido/src/mypy/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/guido/src/mypy/mypy/build.py", line 383, in process
    next.process()
  File "/Users/guido/src/mypy/mypy/build.py", line 823, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 210, in visit_file
    d.accept(self)
  File "/Users/guido/src/mypy/mypy/nodes.py", line 483, in accept
    return visitor.visit_class_def(self)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 460, in visit_class_def
    self.clean_up_bases_and_infer_type_variables(defn)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 593, in clean_up_bases_and_infer_type_variables
    tvars = self.analyze_typevar_declaration(base)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 615, in analyze_typevar_declaration
    if sym.node.fullname() == 'typing.Generic':
AttributeError: 'NoneType' object has no attribute 'fullname'
```
It did not print the name of the file it was analyzing.

**Comment by JukkaL** [comment]
This happened during semantic analysis and it doesn't yet print out context. I just pushed a potential fix. LMK if it fixed the crash.

The problem is related to analyzing the base classes of some class.

**Comment by gvanrossum** [comment]
Alas, no, I get a different tb:
```
  File "/Users/guido/src/mypy/scripts/mypy", line 6, in <module>
    main(__file__)
  File "/Users/guido/src/mypy/mypy/main.py", line 91, in main
    type_check_only(sources, bin_dir, options)
  File "/Users/guido/src/mypy/mypy/main.py", line 134, in type_check_only
    python_path=options.python_path)
  File "/Users/guido/src/mypy/mypy/build.py", line 197, in build
    result = manager.process(initial_states)
  File "/Users/guido/src/mypy/mypy/build.py", line 387, in process
    next.process()
  File "/Users/guido/src/mypy/mypy/build.py", line 827, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 210, in visit_file
    d.accept(self)
  File "/Users/guido/src/mypy/mypy/nodes.py", line 483, in accept
    return visitor.visit_class_def(self)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 465, in visit_class_def
    self.analyze_base_classes(defn)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 652, in analyze_base_classes
    base = self.expr_to_analyzed_type(base_expr)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 705, in expr_to_analyzed_type
    return self.anal_type(typ)
  File "/Users/guido/src/mypy/mypy/semanal.py", line 932, in anal_type
    return t.accept(a)
  File "/Users/guido/src/mypy/mypy/types.py", line 74, in accept
    return visitor.visit_unbound_type(self)
  File "/Users/guido/src/mypy/mypy/typeanal.py", line 75, in visit_unbound_type
    fullname = sym.node.fullname()
AttributeError: 'NoneType' object has no attribute 'fullname'
```

**Comment by JukkaL** [comment]
I pushed another fix that hopefully generates an internal error pointing to the correct line.

**Comment by gvanrossum** [comment]
Yup, that fixed it.

**Comment by gvanrossum** [comment]
Let's close this, the AttributeError is gone.
