### ISSUE TITLE
Crash in list type inference

### ISSUE THREAD

**Issue by gvanrossum** [JukkaL/mypy#1059]
Minimal example:
```
def foo(blocks: Any):
    to_process = []
    to_process = list(blocks)
```
Note that there is no import of Any from typing. If I add the import, the crash disappears. All three lines apparently contribute to the crash. Traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.5/site-packages/mypy/main.py", line 50, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.5/site-packages/mypy/main.py", line 93, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 200, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 383, in process
    next.process()
  File "/usr/local/lib/python3.5/site-packages/mypy/build.py", line 870, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 375, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 384, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/nodes.py", line 380, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 439, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 474, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 557, in check_func_def
    self.accept_in_frame(item.body)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 400, in accept_in_frame
    changed, _ = self.binder.pop_frame(True, True)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 202, in pop_frame
    changed = self.update_from_options(options)
  File "/usr/local/lib/python3.5/site-packages/mypy/checker.py", line 153, in update_from_options
    type = join_simple(self.frames[0][key], type, other)
  File "/usr/local/lib/python3.5/site-packages/mypy/join.py", line 26, in join_simple
    if is_subtype(s, t):
  File "/usr/local/lib/python3.5/site-packages/mypy/subtypes.py", line 49, in is_subtype
    return left.accept(SubtypeVisitor(right, type_parameter_checker))
  File "/usr/local/lib/python3.5/site-packages/mypy/types.py", line 521, in accept
    return visitor.visit_partial_type(self)
  File "/usr/local/lib/python3.5/site-packages/mypy/subtypes.py", line 189, in visit_partial_type
    raise RuntimeError
RuntimeError: 

*** INTERNAL ERROR ***

/Users/guido/mypy_tests/mypy_crash.py:1: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
```

**Comment by JukkaL** [comment]
This is somehow related to the type inference improvement that I pushed yesterday. Marking this as priority as this results in a crash.
