### ISSUE TITLE
internal error with kwargs

### ISSUE THREAD

**Issue by dashea** [JukkaL/mypy#1095]
Encountered while running mypy on something using polib. Here's a reproducer:

```
import textwrap
def wrap(text, width=70, **kwargs):
    return textwrap.wrap(text, width=width, **kwargs)
```

and here's the traceback:

```
Traceback (most recent call last):
  File "/usr/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 50, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/lib/python3.5/site-packages/mypy/main.py", line 93, in type_check_only
    python_path=options.python_path)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 385, in process
    next.process()
  File "/usr/lib/python3.5/site-packages/mypy/build.py", line 882, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 385, in visit_file
    self.accept(d)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 381, in accept
    return visitor.visit_func_def(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 449, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 484, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 567, in check_func_def
    self.accept_in_frame(item.body)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 409, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 525, in accept
    return visitor.visit_block(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 984, in visit_block
    self.accept(s)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 622, in accept
    return visitor.visit_return_stmt(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 1386, in visit_return_stmt
    typ = self.accept(s.expr, self.return_types[-1])
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/lib/python3.5/site-packages/mypy/nodes.py", line 984, in accept
    return visitor.visit_call_expr(self)
  File "/usr/lib/python3.5/site-packages/mypy/checker.py", line 1841, in visit_call_expr
    return self.expr_checker.visit_call_expr(e)
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 126, in visit_call_expr
    return self.check_call_expr_with_callee_type(callee_type, e)
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 177, in check_call_expr_with_callee_type
    e.arg_names, callable_node=e.callee)[0]
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 224, in check_call
    arg_names, formal_to_actual, context)
  File "/usr/lib/python3.5/site-packages/mypy/checkexpr.py", line 535, in check_argument_count
    isinstance(actual_type, TupleType)):
UnboundLocalError: local variable 'actual_type' referenced before assignment

*** INTERNAL ERROR ***

tmp.py:3: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues
```

The problem seems to be in the conditional added in 06753e7c696b254d173a0abf4e61bc443cb3b6b5 but I'm not sure how actual_type should be set in this case or what should be used in its place.

**Comment by gvanrossum** [comment]
I think this is what was intended:
```
 i < len(actual_types) and isinstance(actual_types[i], TupleType)):
```
With that, I don't get an internal error for your code snippet but I do get another error:
```
tmp.py:3: error: Too many positional arguments for "wrap"
```
but that seems due to a bug in the stub file (stdlib/3/textwrap.pyi) in the typeshed repo -- it's missing the `text` positional parameter.

**Comment by dashea** [comment]
Makes sense, though actual_types would have to be initialized to an empty list at some point.

**Comment by gvanrossum** [comment]
Well, `actual_types` is a parameter of type `List[Type]`. Does that satisfy
you?

On Tue, Dec 22, 2015 at 12:47 PM, David Shea <notifications@github.com>
wrote:

> Makes sense, though actual_types would have to be initialized to an empty
> list at some point.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1095#issuecomment-166725903>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by dashea** [comment]
Oh, right. I was getting actual_types and actual_type mixed up. Thanks.

**Comment by gvanrossum** [comment]
FWIW, I spent a bunch of time trying to understand what this code is intending to do, and failed. It does not look like the fix I suggested above is correct. I will get back to this but unfortunately I've got higher priorities (all related to mypy though :-).

**Comment by kirbyfan64** [comment]
Smallest test case:

This works:

```python3
def f(a):
    return

f(1, a=1)
```

This fails:

```python3
def f(a): pass

def g():
    f(1, a=1)
```

**Comment by gvanrossum** [comment]
Thanks -- I had found a similar test case but failed to post it here. The
former gives an error message "f" gets multiple values for keyword argument
"a" right? The latter crashes.

Unfortunately there are a whole bunch of things I could substitute for
actual_type that make the crash go away, but when running unittests they
all seem to cause some test (usually in check-weak-typing.test) to fail.

FWIW if you add "->None" to g() in the latter example it doesn't crash (but
gives the same error message as the former).

On Tue, Jan 12, 2016 at 8:52 AM, Ryan Gonzalez <notifications@github.com>
wrote:

> Smallest test case:
>
> This works:
>
> def f(a):
>     return
>
> f(1, a=1)
>
> This fails:
>
> def f(a): pass
>
> def g():
>     f(1, a=1)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JukkaL/mypy/issues/1095#issuecomment-170972493>.
>



-- 
--Guido van Rossum (python.org/~guido)
