### ISSUE TITLE
Internal error - AttributeError: 'NoneType' object has no attribute 'node'

### ISSUE THREAD

**Issue by mihneagiurgea** [JukkaL/mypy#1156]
Running mypy on this example fails with an internal error:
```
if __name__ == '__main__':
    serversList = []
    for i in serversList:
        def to_s(val):
            if not isinstance(val, basestring):
                return "%s (%s)" % (val, type(val))
            return "%s" % val
        to_s("s")
```

Stacktrace:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/mypy", line 6, in <module>
    main(__file__)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/main.py", line 53, in main
    type_check_only(sources, bin_dir, options)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/main.py", line 96, in type_check_only
    python_path=options.python_path)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 386, in process
    next.process()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/build.py", line 844, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 210, in visit_file
    self.accept(d)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2126, in accept
    node.accept(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 673, in accept
    return visitor.visit_if_stmt(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 1551, in visit_if_stmt
    self.visit_block(s.body[i])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 931, in visit_block
    self.accept(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2126, in accept
    node.accept(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 613, in accept
    return visitor.visit_for_stmt(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 1534, in visit_for_stmt
    self.visit_block(s.body)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 931, in visit_block
    self.accept(s)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 2126, in accept
    node.accept(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/nodes.py", line 382, in accept
    return visitor.visit_func_def(self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mypy/semanal.py", line 264, in visit_func_def
    if isinstance(symbol.node, FuncDef) and symbol.node != defn:
AttributeError: 'NoneType' object has no attribute 'node'
```

Moving the function def outside of the for loop seems to work.

**Comment by kirbyfan64** [comment]
Smaller test case:

```python
for _ in []:
    def f(): pass
```

Basically, it's any function within a `for` loop.

**Comment by kirbyfan64** [comment]
Also, the obvious fix of adding a `symbol and` to the beginning of the condition will cause `f` to be undefined...!?

**Comment by JukkaL** [comment]
I'm looking at this.
