### ISSUE TITLE
mypy crashes running on a directory with shell scripts in it

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1163]
When running mypy on directories in the Zulip open source project that contain shell scripts in addition to python scripts, I got two tracebacks from mypy.  Reproducers below:
```
tabbott@tabbox:/tmp$ git clone git@github.com:zulip/zulip.git
Cloning into 'zulip'...
remote: Counting objects: 69938, done.
remote: Total 69938 (delta 0), reused 0 (delta 0), pack-reused 69938
Receiving objects: 100% (69938/69938), 104.71 MiB | 5.82 MiB/s, done.
Resolving deltas: 100% (48285/48285), done.
Checking connectivity... done.

# First one involves running on a directory
tabbott@tabbox:/tmp$ mypy --py2 --silent zulip/scripts/lib/
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 53, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 96, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 179, in build
    reports = Reports(sources[0].effective_path, data_dir, report_dirs)
IndexError: list index out of range

# Second one involved running mypy explicitly against the 3 files in the directory
tabbott@tabbox:/tmp$ mypy --py2 --silent zulip/bin/write-rabbitmq-consumers-state-file zulip/bin/log-management-command zulip/bin/get-django-setting 
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 53, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.4/dist-packages/mypy/main.py", line 96, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 203, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 386, in process
    next.process()
  File "/usr/local/lib/python3.4/dist-packages/mypy/build.py", line 714, in process
    'Module %s processed twice' % self.id)
AssertionError: Module __main__ processed twice
```

**Comment by gvanrossum** [comment]
The first is because there are no .py files in zulip/scripts/lib/.
I'll fix the error message. :-)

**Comment by gvanrossum** [comment]
The second is because there's no `__init__.py` in that dir, so it
analyzes each file as a `__main__` module. For that the workaround is
to analyze them one at a time; I could try to make the error better
but it's likely complicated.

**Comment by gvanrossum** [comment]
Two separate fixes pushed:
066ffb3e7a673c9674c1b70bad457ef4c51663d1
7217f84e1dc5f2d98fdd357881b8c3b755fe8cc8
