### ISSUE TITLE
Mypy crash running on dropbox/changes.git

### ISSUE THREAD

**Issue by timabbott** [JukkaL/mypy#1192]
```
$ (cd ~/ && git clone git@github.com:dropbox/changes.git)
tabbott@tabbox:~/mypy$ mypy --py2 --silent --implicit-any /home/tabbott/changes/changes/ 
Traceback (most recent call last):
  File "/usr/local/bin/mypy", line 6, in <module>
    main(__file__)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 54, in main
    type_check_only(sources, bin_dir, options)
  File "/usr/local/lib/python3.5/dist-packages/mypy/main.py", line 98, in type_check_only
    python_path=options.python_path)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 206, in build
    result = manager.process(initial_states)
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 392, in process
    next.process()
  File "/usr/local/lib/python3.5/dist-packages/mypy/build.py", line 897, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 385, in visit_file
    self.accept(d)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 485, in accept
    return visitor.visit_class_def(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 963, in visit_class_def
    self.accept(defn.defs)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 382, in accept
    return visitor.visit_func_def(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 509, in visit_func_def
    self.check_func_item(defn, name=defn.name())
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 567, in check_func_item
    self.check_func_def(defn, typ, name)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 663, in check_func_def
    self.accept_in_frame(item.body)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 409, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 707, in accept
    return visitor.visit_try_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1667, in visit_try_stmt
    self.accept(s.body)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 594, in accept
    return visitor.visit_while_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1606, in visit_while_stmt
    repeat_till_fixed=True)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 409, in accept_in_frame
    answer = self.accept(node, type_context)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 673, in accept
    return visitor.visit_if_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1561, in visit_if_stmt
    self.accept(b)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 673, in accept
    return visitor.visit_if_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1561, in visit_if_stmt
    self.accept(b)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 673, in accept
    return visitor.visit_if_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1561, in visit_if_stmt
    self.accept(b)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 526, in accept
    return visitor.visit_block(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1058, in visit_block
    self.accept(s)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 394, in accept
    typ = node.accept(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/nodes.py", line 564, in accept
    return visitor.visit_assignment_stmt(self)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1067, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1109, in check_assignment
    self.check_indexed_assignment(index_lvalue, rvalue, rvalue)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1444, in check_indexed_assignment
    self.try_infer_partial_type_from_indexed_assignment(lvalue, rvalue)
  File "/usr/local/lib/python3.5/dist-packages/mypy/checker.py", line 1460, in try_infer_partial_type_from_indexed_assignment
    typename = cast(Instance, var.type).type.fullname()
AttributeError: 'NoneType' object has no attribute 'fullname'

*** INTERNAL ERROR ***

/home/tabbott/changes/changes/utils/diff_parser.py:71: error: Internal error -- please report a bug at https://github.com/JukkaL/mypy/issues

NOTE: you can use "mypy --pdb ..." to drop into the debugger when this happens.
```

**Comment by gvanrossum** [comment]
A simpler reproducer:
```
from typing import Any

def f() -> Any:
    current_file = None
    current_file[''] = None
```
Just run `mypy` on this, `--implicit-any` is not needed.
