### ISSUE TITLE
Subclassing Tuple

### ISSUE THREAD

**Issue by Stebalien** [JukkaL/mypy#279]
While it is possible to subclass `tuple`, subclassing `Tuple` doesn't actually yield a subclass of `Tuple`.

The following gives the error `Argument 1 to "fn" has incompatible type Test[int]`:
```python
from typing import typevar, Generic, Tuple

T = typevar('T')

class Test(Generic[T], Tuple[T]):
    pass

def fn(arg: Tuple[int]) -> None:
    pass

fn(Test[int]())
```

I would expect this to work because `Test` inherits `Tuple`.

Additionally, the following doesn't work because `Tuple` is an object and can't be indexed:
```python
from typing import typevar, Generic, Tuple

T = typevar('T')

class Test(Generic[T], Tuple[T]):
    pass

assert isinstance(Test[int](), Tuple[int])
```

Both of these examples work with `List`.

**Comment by JukkaL** [comment]
Here's the original program using the current syntax:

```
from typing import TypeVar, Generic, Tuple

T = TypeVar('T')

class Test(Generic[T], Tuple[T]):
    pass

def fn(arg: Tuple[int]) -> None:
    pass

x = Test() # type: Test[int]
fn(x)
```

Now it crashes in the type checker, apparently on the second-to-last line:

```
Traceback (most recent call last):
  File "scripts/mypy", line 182, in <module>
    main()
  File "scripts/mypy", line 36, in main
    type_check_only(path, module, bin_dir, options)
  File "scripts/mypy", line 80, in type_check_only
    python_path=options.python_path)
  File "/home/jukka/project/mypy/mypy/build.py", line 164, in build
    result = manager.process(UnprocessedFile(info, program_text))
  File "/home/jukka/project/mypy/mypy/build.py", line 341, in process
    next.process()
  File "/home/jukka/project/mypy/mypy/build.py", line 775, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/home/jukka/project/mypy/mypy/semanal.py", line 175, in visit_file
    d.accept(self)
  File "/home/jukka/project/mypy/mypy/nodes.py", line 518, in accept
    return visitor.visit_assignment_stmt(self)
  File "/home/jukka/project/mypy/mypy/semanal.py", line 822, in visit_assignment_stmt
    s.type = self.anal_type(s.type)
  File "/home/jukka/project/mypy/mypy/semanal.py", line 813, in anal_type
    return t.accept(a)
  File "/home/jukka/project/mypy/mypy/types.py", line 70, in accept
    return visitor.visit_unbound_type(self)
  File "/home/jukka/project/mypy/mypy/typeanal.py", line 129, in visit_unbound_type
    return TupleType(self.anal_array(info.tuple_type.items),
  File "/home/jukka/project/mypy/mypy/typeanal.py", line 196, in anal_array
    res.append(t.accept(self))
  File "/home/jukka/project/mypy/mypy/types.py", line 197, in accept
    return visitor.visit_type_var(self)
  File "/home/jukka/project/mypy/mypy/typeanal.py", line 151, in visit_type_var
    raise RuntimeError('TypeVarType is already analysed')
RuntimeError: TypeVarType is already analysed
```

**Comment by spkersten** [comment]
Probably I broke this when I moved the binding of type vars around. I'll try to look into it later today.

**Comment by spkersten** [comment]
Apparently I didn't break this :smile:. It got broken quite a while ago by the merge of 'namedtuple' in 29f1009. Last good commit was a99b5e7.

**Comment by JukkaL** [comment]
Thanks for investigating this issue! Apparently this was working for a short while but then I broke it :-(

**Comment by JukkaL** [comment]
PEP 484 doesn't actually support subclassing `Tuple[...]`. Supported base classes include `NamedTuple(...)`, `namedtuple(...)` and `tuple`. Mypy should give an error message if using `Tuple[...]` as a base class.

Also, this should be documented.

**Comment by JukkaL** [comment]
Now mypy complains if you try to use the original example, as it wouldn't work anyway at runtime.
