### ISSUE TITLE
Python 3.4.2 support ?

### ISSUE THREAD

**Issue by douglarek** [JukkaL/mypy#554]
`pip install mypy`

then

```
Downloading/unpacking dbutils (from sqlbean>=0.490->mypy)
  Downloading DBUtils-1.1.tar.gz (109kB): 109kB downloaded
  Running setup.py (path:/Users/lingchax/.virtualenvs/3.4.2/build/dbutils/setup.py) egg_info for package dbutils
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/lingchax/.virtualenvs/3.4.2/build/dbutils/setup.py", line 11, in <module>
        raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)
    ImportError: Python 3.4 is not supported by DBUtils.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/lingchax/.virtualenvs/3.4.2/build/dbutils/setup.py", line 11, in <module>

    raise ImportError('Python %d.%d is not supported by DBUtils.' % py_version)

ImportError: Python 3.4 is not supported by DBUtils.
```

It means DBUtil does not support 3.4 now !

**Comment by kirbyfan64** [comment]
The PyPI package [mypy](https://pypi.python.org/pypi/mypy/0.256) is TOTALLY unrelated; it's a package that hasn't been updated since 2011. What you want is [mypy-lang](https://pypi.python.org/pypi/mypy-lang/0.1.0):

```
pip install mypy-lang
```

**Comment by douglarek** [comment]
@kirbyfan64 Ok, thanks
