### ISSUE TITLE
Wrong tuple types should give a better error message

### ISSUE THREAD

**Issue by lihaoyi** [JukkaL/mypy#802]
```python
def print_tb(traceback: (int, int)) -> None: ...
```
```bash
haoyi-mbp:mypy haoyi$ python3 scripts/mypy --py2 -m testmodule
Traceback (most recent call last):
  File "scripts/mypy", line 184, in <module>
    main()
  File "scripts/mypy", line 36, in main
    type_check_only(path, module, bin_dir, options)
  File "scripts/mypy", line 80, in type_check_only
    python_path=options.python_path)
  File "/Users/haoyi/mypy/mypy/build.py", line 160, in build
    result = manager.process(UnprocessedFile(info, program_text))
  File "/Users/haoyi/mypy/mypy/build.py", line 344, in process
    next.process()
  File "/Users/haoyi/mypy/mypy/build.py", line 754, in process
    self.semantic_analyzer().visit_file(self.tree, self.tree.path)
  File "/Users/haoyi/mypy/mypy/semanal.py", line 196, in visit_file
    d.accept(self)
  File "/Users/haoyi/mypy/mypy/nodes.py", line 349, in accept
    return visitor.visit_func_def(self)
  File "/Users/haoyi/mypy/mypy/semanal.py", line 205, in visit_func_def
    self.update_function_type_variables(defn)
  File "/Users/haoyi/mypy/mypy/semanal.py", line 252, in update_function_type_variables
    typevars = self.infer_type_variables(functype)
  File "/Users/haoyi/mypy/mypy/semanal.py", line 268, in infer_type_variables
    for name, tvar_expr in self.find_type_variables_in_type(arg):
  File "/Users/haoyi/mypy/mypy/semanal.py", line 299, in find_type_variables_in_type
    assert False, 'Unsupported type %s' % type
AssertionError: Unsupported type Tuple[int?, int?]
```

Would be nice to either have it work or have a prettier error message ^_^

**Comment by o11c** [comment]
Making errors prettier is a long-term goal of my fork.
