### ISSUE TITLE
AttributeError: 'Var' object has no attribute 'args'

### ISSUE THREAD

**Issue by jingw** [JukkaL/mypy#834]
```
jing@jing-mba:~/code/mypy$ git diff
diff --git a/stubs/2.7/builtins.pyi b/stubs/2.7/builtins.pyi
index fa88215..ae08b05 100644
--- a/stubs/2.7/builtins.pyi
+++ b/stubs/2.7/builtins.pyi
@@ -531,6 +531,9 @@ class bytearray(Sequence[int]):
     @overload
     def __ge__(self, x: str) -> bool: ...
 
+class buffer(object):
+    def __init__(p_object: Any, offset: int = None, size: int = None) -> None: ...
+
 class bool(int, SupportsInt, SupportsFloat):
     def __init__(self, o: object = False) -> None: ...
```

```
Traceback (most recent call last):
  File "/Users/jing/code/mypy/scripts/mypy", line 184, in <module>
    main()
  File "/Users/jing/code/mypy/scripts/mypy", line 36, in main
    type_check_only(path, module, bin_dir, options)
  File "/Users/jing/code/mypy/scripts/mypy", line 80, in type_check_only
    python_path=options.python_path)
  File "/Users/jing/code/mypy/mypy/build.py", line 160, in build
    result = manager.process(UnprocessedFile(info, program_text))
  File "/Users/jing/code/mypy/mypy/build.py", line 344, in process
    next.process()
  File "/Users/jing/code/mypy/mypy/build.py", line 793, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/Users/jing/code/mypy/mypy/checker.py", line 353, in visit_file
    self.accept(d)
  File "/Users/jing/code/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jing/code/mypy/mypy/nodes.py", line 452, in accept
    return visitor.visit_class_def(self)
  File "/Users/jing/code/mypy/mypy/checker.py", line 834, in visit_class_def
    self.accept(defn.defs)
  File "/Users/jing/code/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jing/code/mypy/mypy/nodes.py", line 493, in accept
    return visitor.visit_block(self)
  File "/Users/jing/code/mypy/mypy/checker.py", line 903, in visit_block
    self.accept(s)
  File "/Users/jing/code/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jing/code/mypy/mypy/nodes.py", line 532, in accept
    return visitor.visit_assignment_stmt(self)
  File "/Users/jing/code/mypy/mypy/checker.py", line 912, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
  File "/Users/jing/code/mypy/mypy/checker.py", line 940, in check_assignment
    self.infer_variable_type(inferred, lvalue, self.accept(rvalue),
  File "/Users/jing/code/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jing/code/mypy/mypy/nodes.py", line 1077, in accept
    return visitor.visit_op_expr(self)
  File "/Users/jing/code/mypy/mypy/checker.py", line 1742, in visit_op_expr
    return self.expr_checker.visit_op_expr(e)
  File "/Users/jing/code/mypy/mypy/checkexpr.py", line 746, in visit_op_expr
    left_type = self.accept(e.left)
  File "/Users/jing/code/mypy/mypy/checkexpr.py", line 1236, in accept
    return self.chk.accept(node, context)
  File "/Users/jing/code/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jing/code/mypy/mypy/nodes.py", line 893, in accept
    return visitor.visit_member_expr(self)
  File "/Users/jing/code/mypy/mypy/checker.py", line 1708, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "/Users/jing/code/mypy/mypy/checkexpr.py", line 677, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/Users/jing/code/mypy/mypy/checkexpr.py", line 690, in analyze_ordinary_member_access
    self.named_type, self.msg)
  File "/Users/jing/code/mypy/mypy/checkmember.py", line 86, in analyze_member_access
    result = analyze_class_attribute_access(itype, name, node, is_lvalue, builtin_type, msg)
  File "/Users/jing/code/mypy/mypy/checkmember.py", line 234, in analyze_class_attribute_access
    return function_type(cast(FuncBase, node.node), builtin_type('builtins.function'))
  File "/Users/jing/code/mypy/mypy/nodes.py", line 1682, in function_type
    for arg in fdef.args:
```

**Comment by jingw** [comment]
@JukkaL 

traced it to code that looks like this
```
class RpcNeedBlocksException(RpcException):
    _params = RpcException._params + ['blocks_needed']
```

**Comment by JukkaL** [comment]
This is fixed in the `hack` branch.
