### ISSUE TITLE
Crash when type checking class attribute access

### ISSUE THREAD

**Issue by JukkaL** [JukkaL/mypy#844]
I get an uncaught exception when I type check this code (thanks to @MichalPokorny for reporting this!):

```
class C:
    x = []

x = C.x
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/jukka/src/mypy/scripts/mypy", line 184, in <module>
    main()
  File "/Users/jukka/src/mypy/scripts/mypy", line 36, in main
    type_check_only(path, module, bin_dir, options)
  File "/Users/jukka/src/mypy/scripts/mypy", line 80, in type_check_only
    python_path=options.python_path)
  File "/Users/jukka/src/mypy/mypy/build.py", line 160, in build
    result = manager.process(UnprocessedFile(info, program_text))
  File "/Users/jukka/src/mypy/mypy/build.py", line 344, in process
    next.process()
  File "/Users/jukka/src/mypy/mypy/build.py", line 795, in process
    self.type_checker().visit_file(self.tree, self.tree.path)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 353, in visit_file
    self.accept(d)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jukka/src/mypy/mypy/nodes.py", line 532, in accept
    return visitor.visit_assignment_stmt(self)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 912, in visit_assignment_stmt
    self.check_assignment(s.lvalues[-1], s.rvalue, s.type is None)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 940, in check_assignment
    self.infer_variable_type(inferred, lvalue, self.accept(rvalue),
  File "/Users/jukka/src/mypy/mypy/checker.py", line 360, in accept
    typ = node.accept(self)
  File "/Users/jukka/src/mypy/mypy/nodes.py", line 893, in accept
    return visitor.visit_member_expr(self)
  File "/Users/jukka/src/mypy/mypy/checker.py", line 1708, in visit_member_expr
    return self.expr_checker.visit_member_expr(e)
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 677, in visit_member_expr
    result = self.analyze_ordinary_member_access(e, False)
  File "/Users/jukka/src/mypy/mypy/checkexpr.py", line 690, in analyze_ordinary_member_access
    self.named_type, self.msg)
  File "/Users/jukka/src/mypy/mypy/checkmember.py", line 86, in analyze_member_access
    result = analyze_class_attribute_access(itype, name, node, is_lvalue, builtin_type, msg)
  File "/Users/jukka/src/mypy/mypy/checkmember.py", line 234, in analyze_class_attribute_access
    return function_type(cast(FuncBase, node.node), builtin_type('builtins.function'))
  File "/Users/jukka/src/mypy/mypy/nodes.py", line 1682, in function_type
    for arg in fdef.args:
AttributeError: 'Var' object has no attribute 'args'
```

**Comment by JukkaL** [comment]
This is a dupe of #834.
