### ISSUE TITLE
setup.py fails if git is not installed

### ISSUE THREAD

**Issue by thomascellerier** [JukkaL/mypy#959]
I clone the mypy master to my local git repository and then commit a zip of it a my "stable" version.

Then I install mypy into a virtualenv to run my tests using that mypy version's `setup.py`. This is also run on a CI build agent which has a minimum amount of packages installed.

Since last week however setup.py seems to require git to install:
```Python
[09:49:10][Step 4/4] Traceback (most recent call last):
[09:49:10][Step 4/4]   File "setup.py", line 16, in <module>
[09:49:10][Step 4/4]     git.verify_git_integrity_or_abort(".")
[09:49:10][Step 4/4]   File "/mypy/mypy/git.py", line 120, in verify_git_integrity_or_abort
[09:49:10][Step 4/4]     if not have_git():
[09:49:10][Step 4/4]   File "/mypy/mypy/git.py", line 18, in have_git
[09:49:10][Step 4/4]     subprocess.check_output(["git", "--help"])
[09:49:10][Step 4/4]   File "/usr/lib/python3.4/subprocess.py", line 603, in check_output
[09:49:10][Step 4/4]     with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
[09:49:10][Step 4/4]   File "/usr/lib/python3.4/subprocess.py", line 848, in __init__
[09:49:10][Step 4/4]     restore_signals, start_new_session)
[09:49:10][Step 4/4]   File "/usr/lib/python3.4/subprocess.py", line 1446, in _execute_child
[09:49:10][Step 4/4]     raise child_exception_type(errno_num, err_msg)
[09:49:10][Step 4/4] FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

Should git really be a requirement to install mypy?

**Comment by matthiaskramm** [comment]
This is a bug. mypy/git.py:have_git() should catch FileNotFoundError.

**Comment by kirbyfan64** [comment]
Isn't Git still needed to checkout the `typeshed` submodule?

**Comment by matthiaskramm** [comment]
It sounded like Thomas builds a zip after cloning both mypy and typeshed. And once that cloning is done, git isn't required anymore.

**Comment by thomascellerier** [comment]
> It sounded like Thomas builds a zip after cloning both mypy and typeshed. And once that cloning is done, git isn't required anymore.

Yes exactly, it works fine now. Thanks for the quick fix!
